In [1]:
import numpy as np 
import pandas as pd

In [18]:


# creating multiindex  object 

#  1  creating multiindex obects 

multiindex=[('Science',90),("Science",8),('Maths',7),('Social',9),("Social",3),('Social',0)]

multi_index_series=pd.MultiIndex.from_tuples(multiindex)

multi_index_series

MultiIndex([('Science', 90),
            ('Science',  8),
            (  'Maths',  7),
            ( 'Social',  9),
            ( 'Social',  3),
            ( 'Social',  0)],
           )

In [7]:


# multiindex object decouple the index 

multi_index_series.levels

FrozenList([['Maths', 'Science', 'Social'], [0, 3, 7, 8, 9, 90]])

In [9]:
multi_index_series.levels[0]

Index(['Maths', 'Science', 'Social'], dtype='object')

In [11]:
multi_index_series.levels[1]

Index([0, 3, 7, 8, 9, 90], dtype='int64')

In [16]:

# pd.MultiIndex.from_product()

# best way

new=pd.MultiIndex.from_product([["social",'science','Maths'],[10,20,30,40,50]])
new

MultiIndex([( 'social', 10),
            ( 'social', 20),
            ( 'social', 30),
            ( 'social', 40),
            ( 'social', 50),
            ('science', 10),
            ('science', 20),
            ('science', 30),
            ('science', 40),
            ('science', 50),
            (  'Maths', 10),
            (  'Maths', 20),
            (  'Maths', 30),
            (  'Maths', 40),
            (  'Maths', 50)],
           )

In [24]:




# creating series with multiindex objects 

mis=pd.Series([1,2,3,4,5,6,7,8,9,10,11,12,13,1,2],index=new)
mis

social   10     1
         20     2
         30     3
         40     4
         50     5
science  10     6
         20     7
         30     8
         40     9
         50    10
Maths    10    11
         20    12
         30    13
         40     1
         50     2
dtype: int64

In [28]:


# fetching items from such series 

mis[('social')]

10    1
20    2
30    3
40    4
50    5
dtype: int64

In [32]:


mis[('Maths',50)]

2

In [40]:



# unstack
# converts multiindex series to data frame 
# converts inner index to columns 
new_dataframe=mis.unstack()

new_dataframe

         10  20  30  40  50
Maths    11  12  13   1   2
science   6   7   8   9  10
social    1   2   3   4   5

In [48]:
new_dataframe.loc['science']

10     6
20     7
30     8
40     9
50    10
Name: science, dtype: int64

In [52]:
new_dataframe.iloc[0]

10    11
20    12
30    13
40     1
50     2
Name: Maths, dtype: int64

In [54]:



# converting back to multiindex series using stack

new_dataframe.stack()

Maths    10    11
         20    12
         30    13
         40     1
         50     2
science  10     6
         20     7
         30     8
         40     9
         50    10
social   10     1
         20     2
         30     3
         40     4
         50     5
dtype: int64

In [68]:




# creating mutiindex dataframe 

# multiindex objects
new=pd.MultiIndex.from_product([["social",'science','Maths'],[10,20,30,40,50]])


horaa=pd.DataFrame(
    [[10,20,30],
     [11,22,30],
      [10,23,30],
      [10,40,30],
      [10,40,30],
      [10,40,30],
      [10,40,30],
      [10,40,30],
      [10,40,30],
      [10,40,30],
      [10,40,30],
      [10,40,30],
      [10,40,30],
      [10,40,30],
      [10,40,30]],columns=['package','marks','year_of service'],index=new
      
)
horaa

            package  marks  year_of service
social  10       10     20               30
        20       11     22               30
        30       10     23               30
        40       10     40               30
        50       10     40               30
science 10       10     40               30
        20       10     40               30
        30       10     40               30
        40       10     40               30
        50       10     40               30
Maths   10       10     40               30
        20       10     40               30
        30       10     40               30
        40       10     40               30
        50       10     40               30

In [70]:
horaa.loc['Maths']

    package  marks  year_of service
10       10     40               30
20       10     40               30
30       10     40               30
40       10     40               30
50       10     40               30

In [72]:
horaa.iloc[1]

package            11
marks              22
year_of service    30
Name: (social, 20), dtype: int64

In [78]:
horaa.loc['social','package']

10    10
20    11
30    10
40    10
50    10
Name: package, dtype: int64

In [86]:



# creating mutiindex dataframe using both rows and columns 

new=pd.MultiIndex.from_product([["social",'science','Maths'],[10,20,30,40,50]])


drs=pd.DataFrame(
    [[10,20,30,0,0,0],
     [11,22,30,0,0,0],
      [10,23,30,0,0,0],
      [10,40,30,0,0,0],
      [10,40,30,0,0,0],
      [10,40,30,0,0,0],
      [10,40,30,0,0,0],
      [10,40,30,0,0,0],
      [10,40,30,0,0,0],
      [10,40,30,0,0,0],
      [10,40,30,0,0,0],
      [10,40,30,0,0,0],
      [10,40,30,0,0,0],
      [10,40,30,0,0,0],
      [10,40,30,0,0,0]],columns=pd.MultiIndex.from_product([['Kathmandu','Pokhara'],['package','marks','year_of service']]),index=new
      
)
drs

           Kathmandu                       Pokhara
             package marks year_of service package marks year_of service
social  10        10    20              30       0     0               0
        20        11    22              30       0     0               0
        30        10    23              30       0     0               0
        40        10    40              30       0     0               0
        50        10    40              30       0     0               0
science 10        10    40              30       0     0               0
        20        10    40              30       0     0               0
        30        10    40              30       0     0               0
        40        10    40              30       0     0               0
        50        10    40              30       0     0               0
Maths   10        10    40              30       0     0               0
        20        10    40              30       0     0               0
        30        10    40              30       0     0               0
        40        10    40              30       0     0               0
        50        10    40              30       0     0               0

In [ ]:


# stacking and unstacking

new=pd.MultiIndex.from_product([["social",'science','Maths'],[10,20,30,40,50]])


horaa=pd.DataFrame(
    [[10,20,30],
     [11,22,30],
      [10,23,30],
      [10,40,30],
      [10,40,30],
      [10,40,30],
      [10,40,30],
      [10,40,30],
      [10,40,30],
      [10,40,30],
      [10,40,30],
      [10,40,30],
      [10,40,30],
      [10,40,30],
      [10,40,30]],columns=['package','marks','year_of service'],index=new

In [89]:
horaa.unstack()

        package                 marks                 year_of service          \
             10  20  30  40  50    10  20  30  40  50              10  20  30
Maths        10  10  10  10  10    40  40  40  40  40              30  30  30
science      10  10  10  10  10    40  40  40  40  40              30  30  30
social       10  11  10  10  10    20  22  23  40  40              30  30  30


         40  50
Maths    30  30
science  30  30
social   30  30

In [91]:
horaa.unstack().unstack()

package          10  Maths      10
                     science    10
                     social     10
                 20  Maths      10
                     science    10
                     social     11
                 30  Maths      10
                     science    10
                     social     10
                 40  Maths      10
                     science    10
                     social     10
                 50  Maths      10
                     science    10
                     social     10
marks            10  Maths      40
                     science    40
                     social     20
                 20  Maths      40
                     science    40
                     social     22
                 30  Maths      40
                     science    40
                     social     23
                 40  Maths      40
                     science    40
                     social     40
                 50  Maths      40
                     science    40
                     social     40
year_of service  10  Maths      30
                     science    30
                     social     30
                 20  Maths      30
                     science    30
                     social     30
                 30  Maths      30
                     science    30
                     social     30
                 40  Maths      30
                     science    30
                     social     30
                 50  Maths      30
                     science    30
                     social     30
dtype: int64

In [ ]:



# stacking does not apply in series

In [93]:


# stacking
horaa.unstack().stack()

C:\Users\acer\AppData\Local\Temp\ipykernel_16960\974695719.py:2: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  horaa.unstack().stack()

            package  marks  year_of service
Maths   10       10     40               30
        20       10     40               30
        30       10     40               30
        40       10     40               30
        50       10     40               30
science 10       10     40               30
        20       10     40               30
        30       10     40               30
        40       10     40               30
        50       10     40               30
social  10       10     20               30
        20       11     22               30
        30       10     23               30
        40       10     40               30
        50       10     40               30

In [95]:
horaa.unstack().stack().stack()

C:\Users\acer\AppData\Local\Temp\ipykernel_16960\1047319930.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  horaa.unstack().stack().stack()

Maths    10  package            10
             marks              40
             year_of service    30
         20  package            10
             marks              40
             year_of service    30
         30  package            10
             marks              40
             year_of service    30
         40  package            10
             marks              40
             year_of service    30
         50  package            10
             marks              40
             year_of service    30
science  10  package            10
             marks              40
             year_of service    30
         20  package            10
             marks              40
             year_of service    30
         30  package            10
             marks              40
             year_of service    30
         40  package            10
             marks              40
             year_of service    30
         50  package            10
             marks              40
             year_of service    30
social   10  package            10
             marks              20
             year_of service    30
         20  package            11
             marks              22
             year_of service    30
         30  package            10
             marks              23
             year_of service    30
         40  package            10
             marks              40
             year_of service    30
         50  package            10
             marks              40
             year_of service    30
dtype: int64

In [97]:
horaa.unstack().stack(future_stack=True).stack(future_stack=True)

Maths    10  package            10
             marks              40
             year_of service    30
         20  package            10
             marks              40
             year_of service    30
         30  package            10
             marks              40
             year_of service    30
         40  package            10
             marks              40
             year_of service    30
         50  package            10
             marks              40
             year_of service    30
science  10  package            10
             marks              40
             year_of service    30
         20  package            10
             marks              40
             year_of service    30
         30  package            10
             marks              40
             year_of service    30
         40  package            10
             marks              40
             year_of service    30
         50  package            10
             marks              40
             year_of service    30
social   10  package            10
             marks              20
             year_of service    30
         20  package            11
             marks              22
             year_of service    30
         30  package            10
             marks              23
             year_of service    30
         40  package            10
             marks              40
             year_of service    30
         50  package            10
             marks              40
             year_of service    30
dtype: int64

In [99]:



# working with multiindex dataframes 

drs

           Kathmandu                       Pokhara
             package marks year_of service package marks year_of service
social  10        10    20              30       0     0               0
        20        11    22              30       0     0               0
        30        10    23              30       0     0               0
        40        10    40              30       0     0               0
        50        10    40              30       0     0               0
science 10        10    40              30       0     0               0
        20        10    40              30       0     0               0
        30        10    40              30       0     0               0
        40        10    40              30       0     0               0
        50        10    40              30       0     0               0
Maths   10        10    40              30       0     0               0
        20        10    40              30       0     0               0
        30        10    40              30       0     0               0
        40        10    40              30       0     0               0
        50        10    40              30       0     0               0

In [101]:
drs.head()

          Kathmandu                       Pokhara
            package marks year_of service package marks year_of service
social 10        10    20              30       0     0               0
       20        11    22              30       0     0               0
       30        10    23              30       0     0               0
       40        10    40              30       0     0               0
       50        10    40              30       0     0               0

In [103]:
drs.tail(2)

         Kathmandu                       Pokhara
           package marks year_of service package marks year_of service
Maths 40        10    40              30       0     0               0
      50        10    40              30       0     0               0

In [105]:
drs.shape

(15, 6)

In [109]:
drs.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 15 entries, ('social', 10) to ('Maths', 50)
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   (Kathmandu, package)          15 non-null     int64
 1   (Kathmandu, marks)            15 non-null     int64
 2   (Kathmandu, year_of service)  15 non-null     int64
 3   (Pokhara, package)            15 non-null     int64
 4   (Pokhara, marks)              15 non-null     int64
 5   (Pokhara, year_of service)    15 non-null     int64
dtypes: int64(6)
memory usage: 1.1+ KB

In [113]:
drs.describe()

       Kathmandu                            Pokhara
         package      marks year_of service package marks year_of service
count  15.000000  15.000000            15.0    15.0  15.0            15.0
mean   10.066667  36.333333            30.0     0.0   0.0             0.0
std     0.258199   7.612646             0.0     0.0   0.0             0.0
min    10.000000  20.000000            30.0     0.0   0.0             0.0
25%    10.000000  40.000000            30.0     0.0   0.0             0.0
50%    10.000000  40.000000            30.0     0.0   0.0             0.0
75%    10.000000  40.000000            30.0     0.0   0.0             0.0
max    11.000000  40.000000            30.0     0.0   0.0             0.0

In [115]:
drs.duplicated()

social   10    False
         20    False
         30    False
         40    False
         50     True
science  10     True
         20     True
         30     True
         40     True
         50     True
Maths    10     True
         20     True
         30     True
         40     True
         50     True
dtype: bool

In [117]:
drs.isnull()

           Kathmandu                        Pokhara
             package  marks year_of service package  marks year_of service
social  10     False  False           False   False  False           False
        20     False  False           False   False  False           False
        30     False  False           False   False  False           False
        40     False  False           False   False  False           False
        50     False  False           False   False  False           False
science 10     False  False           False   False  False           False
        20     False  False           False   False  False           False
        30     False  False           False   False  False           False
        40     False  False           False   False  False           False
        50     False  False           False   False  False           False
Maths   10     False  False           False   False  False           False
        20     False  False           False   False  False           False
        30     False  False           False   False  False           False
        40     False  False           False   False  False           False
        50     False  False           False   False  False           False

In [119]:


# extracting single row 
drs.loc[('social',50)]

Kathmandu  package            10
           marks              40
           year_of service    30
Pokhara    package             0
           marks               0
           year_of service     0
Name: (social, 50), dtype: int64

In [149]:



# extracting multiple rows 

# pd.IndexSlice
# is a special Pandas object that tells .loc:
# sorting first
# I am going to slice MultiIndex levels, not just single labels.”
drs = drs.sort_index()
idx=pd.IndexSlice
drs.loc[idx['social':'science', 10:50],:]

Empty DataFrame
Columns: [(Kathmandu, package), (Kathmandu, marks), (Kathmandu, year_of service), (Pokhara, package), (Pokhara, marks), (Pokhara, year_of service)]
Index: []

In [133]:
drs1=drs.sort_index()
drs1.loc[('social',10):('science',50)]

Empty DataFrame
Columns: [(Kathmandu, package), (Kathmandu, marks), (Kathmandu, year_of service), (Pokhara, package), (Pokhara, marks), (Pokhara, year_of service)]
Index: []

In [135]:



# using iloc

drs.iloc[0,5:2]

Series([], Name: (social, 10), dtype: float64)

In [155]:



# extracting cons

drs['Kathmandu']

            package  marks  year_of service
Maths   10       10     40               30
        20       10     40               30
        30       10     40               30
        40       10     40               30
        50       10     40               30
science 10       10     40               30
        20       10     40               30
        30       10     40               30
        40       10     40               30
        50       10     40               30
social  10       10     20               30
        20       11     22               30
        30       10     23               30
        40       10     40               30
        50       10     40               30

In [161]:
drs['Kathmandu']['marks']

Maths    10    40
         20    40
         30    40
         40    40
         50    40
science  10    40
         20    40
         30    40
         40    40
         50    40
social   10    20
         20    22
         30    23
         40    40
         50    40
Name: marks, dtype: int64

In [165]:

# [rows,clomns]
drs.iloc[:,3:5]

           Pokhara
           package marks
Maths   10       0     0
        20       0     0
        30       0     0
        40       0     0
        50       0     0
science 10       0     0
        20       0     0
        30       0     0
        40       0     0
        50       0     0
social  10       0     0
        20       0     0
        30       0     0
        40       0     0
        50       0     0

In [167]:


drs.iloc[:, [3, 5]]

           Pokhara
           package year_of service
Maths   10       0               0
        20       0               0
        30       0               0
        40       0               0
        50       0               0
science 10       0               0
        20       0               0
        30       0               0
        40       0               0
        50       0               0
social  10       0               0
        20       0               0
        30       0               0
        40       0               0
        50       0               0

In [169]:
# slicing in both rows and columns 

drs.iloc[2:7, [3, 5]]

           Pokhara
           package year_of service
Maths   30       0               0
        40       0               0
        50       0               0
science 10       0               0
        20       0               0

In [171]:




# sort_index()

# both level 0 nad level 1
drs.sort_index(ascending=False)

           Kathmandu                       Pokhara
             package marks year_of service package marks year_of service
social  50        10    40              30       0     0               0
        40        10    40              30       0     0               0
        30        10    23              30       0     0               0
        20        11    22              30       0     0               0
        10        10    20              30       0     0               0
science 50        10    40              30       0     0               0
        40        10    40              30       0     0               0
        30        10    40              30       0     0               0
        20        10    40              30       0     0               0
        10        10    40              30       0     0               0
Maths   50        10    40              30       0     0               0
        40        10    40              30       0     0               0
        30        10    40              30       0     0               0
        20        10    40              30       0     0               0
        10        10    40              30       0     0               0

In [173]:


# sorting differently

drs.sort_index(ascending=[False,True])

           Kathmandu                       Pokhara
             package marks year_of service package marks year_of service
social  10        10    20              30       0     0               0
        20        11    22              30       0     0               0
        30        10    23              30       0     0               0
        40        10    40              30       0     0               0
        50        10    40              30       0     0               0
science 10        10    40              30       0     0               0
        20        10    40              30       0     0               0
        30        10    40              30       0     0               0
        40        10    40              30       0     0               0
        50        10    40              30       0     0               0
Maths   10        10    40              30       0     0               0
        20        10    40              30       0     0               0
        30        10    40              30       0     0               0
        40        10    40              30       0     0               0
        50        10    40              30       0     0               0

In [179]:


# sorting on one  level only

drs.sort_index(level=1,ascending=[False])

           Kathmandu                       Pokhara
             package marks year_of service package marks year_of service
Maths   50        10    40              30       0     0               0
science 50        10    40              30       0     0               0
social  50        10    40              30       0     0               0
Maths   40        10    40              30       0     0               0
science 40        10    40              30       0     0               0
social  40        10    40              30       0     0               0
Maths   30        10    40              30       0     0               0
science 30        10    40              30       0     0               0
social  30        10    23              30       0     0               0
Maths   20        10    40              30       0     0               0
science 20        10    40              30       0     0               0
social  20        11    22              30       0     0               0
Maths   10        10    40              30       0     0               0
science 10        10    40              30       0     0               0
social  10        10    20              30       0     0               0

In [181]:



# transpose     

# converting rows to columns and vice versa


drs.transpose()

                          Maths                 science                  \
                             10  20  30  40  50      10  20  30  40  50
Kathmandu package            10  10  10  10  10      10  10  10  10  10
          marks              40  40  40  40  40      40  40  40  40  40
          year_of service    30  30  30  30  30      30  30  30  30  30
Pokhara   package             0   0   0   0   0       0   0   0   0   0
          marks               0   0   0   0   0       0   0   0   0   0
          year_of service     0   0   0   0   0       0   0   0   0   0

                          social
                              10  20  30  40  50
Kathmandu package             10  11  10  10  10
          marks               20  22  23  40  40
          year_of service     30  30  30  30  30
Pokhara   package              0   0   0   0   0
          marks                0   0   0   0   0
          year_of service      0   0   0   0   0

In [183]:


# swaplevel


# swapping  level o and 1


# for rows 

# default axis =o
drs.swaplevel()

           Kathmandu                       Pokhara
             package marks year_of service package marks year_of service
10 Maths          10    40              30       0     0               0
20 Maths          10    40              30       0     0               0
30 Maths          10    40              30       0     0               0
40 Maths          10    40              30       0     0               0
50 Maths          10    40              30       0     0               0
10 science        10    40              30       0     0               0
20 science        10    40              30       0     0               0
30 science        10    40              30       0     0               0
40 science        10    40              30       0     0               0
50 science        10    40              30       0     0               0
10 social         10    20              30       0     0               0
20 social         11    22              30       0     0               0
30 social         10    23              30       0     0               0
40 social         10    40              30       0     0               0
50 social         10    40              30       0     0               0

In [185]:


# swapping level of columns 

drs.swaplevel(axis=1)

             package     marks year_of service package   marks year_of service
           Kathmandu Kathmandu       Kathmandu Pokhara Pokhara         Pokhara
Maths   10        10        40              30       0       0               0
        20        10        40              30       0       0               0
        30        10        40              30       0       0               0
        40        10        40              30       0       0               0
        50        10        40              30       0       0               0
science 10        10        40              30       0       0               0
        20        10        40              30       0       0               0
        30        10        40              30       0       0               0
        40        10        40              30       0       0               0
        50        10        40              30       0       0               0
social  10        10        20              30       0       0               0
        20        11        22              30       0       0               0
        30        10        23              30       0       0               0
        40        10        40              30       0       0               0
        50        10        40              30       0       0               0

In [189]:


# melt 
#wide to long 




a=pd.DataFrame({
    'name':['Ashish','Manish','Sital'],
    'Age':[10,20,30]
})
a

     name  Age
0  Ashish   10
1  Manish   20
2   Sital   30

In [191]:
a.melt()

  variable   value
0     name  Ashish
1     name  Manish
2     name   Sital
3      Age      10
4      Age      20
5      Age      30

In [195]:
a.melt(id_vars='name')  # id_vars skips the coloumn

     name variable  value
0  Ashish      Age     10
1  Manish      Age     20
2   Sital      Age     30

In [199]:
a.melt(id_vars='name',value_name='info',var_name='AGE_info')

     name AGE_info  info
0  Ashish      Age    10
1  Manish      Age    20
2   Sital      Age    30

In [201]:



# real world data 


covid=pd.read_csv(r"C:\Users\acer\Python-Sql-1\numpy_pandas_matplotlib_seaborn\dataset for mutliindex_series\time_series_covid19_confirmed_global.csv")
death=pd.read_csv(r"C:\Users\acer\Python-Sql-1\numpy_pandas_matplotlib_seaborn\dataset for mutliindex_series\time_series_covid19_deaths_global.csv")

In [205]:



covid.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,207310,207399,207438,207460,207493,207511,207550,207559,207616,207627
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,333749,333749,333751,333751,333776,333776,333806,333806,333811,333812
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,271194,271198,271198,271202,271208,271217,271223,271228,271229,271229
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,47686,47686,47686,47686,47751,47751,47751,47751,47751,47751
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,104973,104973,104973,105095,105095,105095,105095,105095,105095,105095

In [207]:
death.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,7845,7846,7846,7846,7846,7847,7847,7849,7849,7849
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,3595,3595,3595,3595,3595,3595,3595,3595,3595,3595
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,6881,6881,6881,6881,6881,6881,6881,6881,6881,6881
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,165,165,165,165,165,165,165,165,165,165
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,1928,1928,1928,1930,1930,1930,1930,1930,1930,1930

In [209]:
death.shape

(289, 1081)

In [217]:


death=death.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='Date',value_name='death_confirmed')
death

,Province/State,Country/Region,Lat,Long,Date,death_confirmed
0,NaN,Afghanistan,33.939110,67.709953,1/22/20,0
1,NaN,Albania,41.153300,20.168300,1/22/20,0
2,NaN,Algeria,28.033900,1.659600,1/22/20,0
3,NaN,Andorra,42.506300,1.521800,1/22/20,0
4,NaN,Angola,-11.202700,17.873900,1/22/20,0
...,...,...,...,...,...,...
311248,NaN,West Bank and Gaza,31.952200,35.233200,1/2/23,5708
311249,NaN,Winter Olympics 2022,39.904200,116.407400,1/2/23,0
311250,NaN,Yemen,15.552727,48.516388,1/2/23,2159
311251,NaN,Zambia,-13.133897,27.849332,1/2/23,4024
311252,NaN,Zimbabwe,-19.015438,29.154857,1/2/23,5637

In [219]:
covid=covid.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='Date',value_name='cases_register')
covid

,Province/State,Country/Region,Lat,Long,Date,cases_register
0,NaN,Afghanistan,33.939110,67.709953,1/22/20,0
1,NaN,Albania,41.153300,20.168300,1/22/20,0
2,NaN,Algeria,28.033900,1.659600,1/22/20,0
3,NaN,Andorra,42.506300,1.521800,1/22/20,0
4,NaN,Angola,-11.202700,17.873900,1/22/20,0
...,...,...,...,...,...,...
311248,NaN,West Bank and Gaza,31.952200,35.233200,1/2/23,703228
311249,NaN,Winter Olympics 2022,39.904200,116.407400,1/2/23,535
311250,NaN,Yemen,15.552727,48.516388,1/2/23,11945
311251,NaN,Zambia,-13.133897,27.849332,1/2/23,334661
311252,NaN,Zimbabwe,-19.015438,29.154857,1/2/23,259981

In [221]:
covid.merge(death,on=['Province/State','Country/Region','Lat','Long','Date'])

,Province/State,Country/Region,Lat,Long,Date,cases_register,death_confirmed
0,NaN,Afghanistan,33.939110,67.709953,1/22/20,0,0
1,NaN,Albania,41.153300,20.168300,1/22/20,0,0
2,NaN,Algeria,28.033900,1.659600,1/22/20,0,0
3,NaN,Andorra,42.506300,1.521800,1/22/20,0,0
4,NaN,Angola,-11.202700,17.873900,1/22/20,0,0
...,...,...,...,...,...,...,...
311248,NaN,West Bank and Gaza,31.952200,35.233200,1/2/23,703228,5708
311249,NaN,Winter Olympics 2022,39.904200,116.407400,1/2/23,535,0
311250,NaN,Yemen,15.552727,48.516388,1/2/23,11945,2159
311251,NaN,Zambia,-13.133897,27.849332,1/2/23,334661,4024
311252,NaN,Zimbabwe,-19.015438,29.154857,1/2/23,259981,5637